# File .github/workflows/deploy.yml
name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: 3.10 }

      - run: pip install -r requirements.txt

      - name: Clean existing docs
        run: rm -rf docs/* # Giữ lại thư mục docs nhưng xóa nội dung

      - run: python generate.py

      - uses: actions/upload-pages-artifact@v2
        with: { path: "docs" }

      - uses: actions/deploy-pages@v3
